

require( "ruanjianwaibaojiaoyisuo/public/modal/rewardreply" )
require( "ruanjianwaibaojiaoyisuo/public/modal/product" )
require( "ruanjianwaibaojiaoyisuo/public/modal/service" )
require( "ruanjianwaibaojiaoyisuo/public/modal/forum" )
require( "ruanjianwaibaojiaoyisuo/public/modal/forumcomment" )
require( "ruanjianwaibaojiaoyisuo/public/modal/threadtype" )
require( "ruanjianwaibaojiaoyisuo/public/modal/user" )
require( "ruanjianwaibaojiaoyisuo/public/modal/ranklist" )
require( "ruanjianwaibaojiaoyisuo/public/modal/reward" )
require( "ruanjianwaibaojiaoyisuo/public/modal/forumforum" )
require( "ruanjianwaibaojiaoyisuo/public/modal/rewardmgr" )
require( "ruanjianwaibaojiaoyisuo/public/modal/forumforummgr" )
require( "ruanjianwaibaojiaoyisuo/public/modal/usermgr" )
require( "ruanjianwaibaojiaoyisuo/public/modal/productmgr" )
require( "ruanjianwaibaojiaoyisuo/public/modal/threadtypemgr" )
require( "ruanjianwaibaojiaoyisuo/public/modal/ranklistmgr" )
require( "ruanjianwaibaojiaoyisuo/public/modal/rewardreplymgr" )
require( "ruanjianwaibaojiaoyisuo/public/modal/forumcommentmgr" )
require( "ruanjianwaibaojiaoyisuo/public/modal/forummgr" )
require( "ruanjianwaibaojiaoyisuo/public/modal/servicemgr" )
require( "ruanjianwaibaojiaoyisuo/public/modal/clsforumforummgr" )
require( "ruanjianwaibaojiaoyisuo/public/modal/clsproductmgr" )
require( "ruanjianwaibaojiaoyisuo/public/modal/clsforummgr" )
require( "ruanjianwaibaojiaoyisuo/public/modal/clsthreadtypemgr" )
require( "ruanjianwaibaojiaoyisuo/public/modal/clsusermgr" )
require( "ruanjianwaibaojiaoyisuo/public/modal/clsranklistmgr" )
require( "ruanjianwaibaojiaoyisuo/public/modal/clsrewardmgr" )
require( "ruanjianwaibaojiaoyisuo/public/modal/clsforumcommentmgr" )
require( "ruanjianwaibaojiaoyisuo/public/modal/clsservicemgr" )
require( "ruanjianwaibaojiaoyisuo/public/modal/clsrewardreplymgr" )

require( "ruanjianwaibaojiaoyisuo/public/modal/profile" )
require( "ruanjianwaibaojiaoyisuo/public/modal/profilemgr" )
require( "ruanjianwaibaojiaoyisuo/public/modal/clsprofilemgr" )

gm_ruanjianwaibaojiaoyisuo.clsforumforummgr.get_instance()
gm_ruanjianwaibaojiaoyisuo.clsproductmgr.get_instance()
gm_ruanjianwaibaojiaoyisuo.clsforummgr.get_instance()
gm_ruanjianwaibaojiaoyisuo.clsthreadtypemgr.get_instance()
gm_ruanjianwaibaojiaoyisuo.clsusermgr.get_instance()
gm_ruanjianwaibaojiaoyisuo.clsranklistmgr.get_instance()
gm_ruanjianwaibaojiaoyisuo.clsrewardmgr.get_instance()
gm_ruanjianwaibaojiaoyisuo.clsforumcommentmgr.get_instance()
gm_ruanjianwaibaojiaoyisuo.clsservicemgr.get_instance()
gm_ruanjianwaibaojiaoyisuo.clsrewardreplymgr.get_instance()
