
require("base/middle/area/script/advmulbig")
require("base/middle/area/script/categarylistarea")
require("base/middle/area/script/categarylistbigarea")
require("base/middle/area/script/categarylistmiddlearea")
require("base/middle/area/script/categarylistsmallarea")
require("base/middle/area/script/objectdesclistarea")
require("base/middle/area/script/categarylistpagebigarea")
require("base/middle/area/script/categarylistpagemiddlearea")
require("base/middle/area/script/categarylistpagesmallarea")
require("base/middle/area/script/threeobjectdescconciseleftarea")
require("base/middle/area/script/threeobjectdescconciserightarea")
require("base/middle/area/script/ursconcisearea")
require("base/middle/area/script/urslistarea")
require("base/middle/area/script/weatherarea")
require("base/middle/area/script/firstarea")