require( "xinbanchunzhongyun/public/modal/cgfscript" )
require( "xinbanchunzhongyun/public/modal/cgfuser" )
require( "xinbanchunzhongyun/public/modal/cgforder" )
require( "xinbanchunzhongyun/public/modal/cgfcustomer" )
require( "xinbanchunzhongyun/public/modal/cgfcustomermgr" )
require( "xinbanchunzhongyun/public/modal/cgfusermgr" )
require( "xinbanchunzhongyun/public/modal/cgfordermgr" )
require( "xinbanchunzhongyun/public/modal/cgfscriptmgr" )
require( "xinbanchunzhongyun/public/modal/clscgfusermgr" )
require( "xinbanchunzhongyun/public/modal/clscgfscriptmgr" )
require( "xinbanchunzhongyun/public/modal/clscgfcustomermgr" )
require( "xinbanchunzhongyun/public/modal/clscgfordermgr" )
gm_xinbanchunzhongyun.clscgfusermgr.get_instance()
gm_xinbanchunzhongyun.clscgfscriptmgr.get_instance()
gm_xinbanchunzhongyun.clscgfcustomermgr.get_instance()
gm_xinbanchunzhongyun.clscgfordermgr.get_instance()
